branch-defaults:
  default:
    environment: x22217029cpp-env
    group_suffix: null
global:
  application_name: x22217029_cpp_energytracker
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
